### ISSUE TITLE
Loot table configs not applying for modded structures

### ISSUE THREAD

**Issue by chimericdream** [Focamacho/RingsOfAscension#33]
For our custom modpack, we were trying to add rings to the loot tables for different modded structures, dungeons, etc. However, it appears that RoA won't add to any loot tables except for those provided by Minecraft itself.

I reproduced this with a minimal setup that included RoA, Dungeons Plus, JEI, and nothing else (except for required dependencies). Here is the mod list and sample config for RoA that I was trying to use to test generation:

Forge: 36.1.0
Curios API: 4.0.5.1
Dungeons Plus: 1.1.4
JEI: 7.7.0.98
Rings of Ascension: 1.6.0
Structure Gel API: 1.7.7

Let me know if you need anything else. Thanks!

<details>
<summary><code>ringsofascension-common.toml</code></summary>

```toml
["Rings of Ascension"]
	#The amount of hearts that Max Health's ring gives you.
	#Range: 0 ~ 400
	ringHealthHearts = 10
	#The cooldown in seconds of the Ring of Undying
	#Range: > 0
	ringUndyingCooldown = 600

["Enable/Disable Rings"]
	ringWaterWalking = true
	ringMagnetism = true
	ringSponge = true
	ringNightVision = true
	ringRegeneration = true
	ringPoisonResistance = true
	ringStrength = true
	ringGrowth = true
	ringInvisibility = true
	ringWaterBreathing = true
	ringWither = true
	ringDolphin = true
	ringKnockbackResistance = true
	ringHungerless = true
	ringFireResistance = true
	ringExperience = true
	ringMining = true
	ringHealth = true
	ringSlowResistance = true
	ringJumpBoost = true
	ringLuck = true
	ringSpeed = true
	ringUndying = true
	ringSlowFalling = true
	ringFlight = true

["Rings Amplifier"]

	#Sets the amplifier of the effect given by the ring. Example:
	#0 = Fire Resistance I
	#1 = Fire Resistance II
	["Rings Amplifier".Amplifiers]
		#Range: 0 ~ 255
		ringAmplifierSlowFalling = 0
		#Range: 0 ~ 255
		ringAmplifierJumpBoost = 0
		#Range: 0 ~ 255
		ringAmplifierDolphin = 0
		#Range: 0 ~ 255
		ringAmplifierInvisibility = 0
		#Range: 0 ~ 255
		ringAmplifierWaterBreathing = 1
		#Range: 0 ~ 255
		ringAmplifierLuck = 1
		#Range: 0 ~ 255
		ringAmplifierRegeneration = 0
		#Range: 0 ~ 255
		ringAmplifierFireResistance = 1
		#Range: 0 ~ 255
		ringAmplifierStrength = 0
		#Range: 0 ~ 255
		ringAmplifierMining = 1
		#Range: 0 ~ 255
		ringAmplifierSpeed = 0
		#Range: 0 ~ 255
		ringAmplifierNightVision = 0

["Rings Tier"]

	#Sets the Tier of the rings. Higher tier rings are more difficult to find.
	#0 = Common
	#1 = Rare
	#2 = Epic
	#3 = Legendary
	#4 = Mythic
	["Rings Tier".Tiers]
		#Range: 0 ~ 4
		ringTierWaterBreathing = 0
		#Range: 0 ~ 4
		ringTierKnockbackResistance = 0
		#Range: 0 ~ 4
		ringTierNightVision = 0
		#Range: 0 ~ 4
		ringTierPoisonResistance = 2
		#Range: 0 ~ 4
		ringTierSlowFalling = 0
		#Range: 0 ~ 4
		ringTierMagnetism = 2
		#Range: 0 ~ 4
		ringTierSponge = 1
		#Range: 0 ~ 4
		ringTierSpeed = 1
		#Range: 0 ~ 4
		ringTierWither = 1
		#Range: 0 ~ 4
		ringTierHealth = 3
		#Range: 0 ~ 4
		ringTierLuck = 3
		#Range: 0 ~ 4
		ringTierRegeneration = 3
		#Range: 0 ~ 4
		ringTierDolphin = 1
		#Range: 0 ~ 4
		ringTierWaterWalking = 0
		#Range: 0 ~ 4
		ringTierInvisibility = 1
		#Range: 0 ~ 4
		ringTierGrowth = 2
		#Range: 0 ~ 4
		ringTierMining = 2
		#Range: 0 ~ 4
		ringTierUndying = 4
		#Range: 0 ~ 4
		ringTierFireResistance = 0
		#Range: 0 ~ 4
		ringTierStrength = 2
		#Range: 0 ~ 4
		ringTierHungerless = 3
		#Range: 0 ~ 4
		ringTierJumpBoost = 0
		#Range: 0 ~ 4
		ringTierSlowResistance = 1
		#Range: 0 ~ 4
		ringTierFlight = 4
		#Range: 0 ~ 4
		ringTierExperience = 0

["Rings Loot"]
	#The maximum number of rings that can be found inside a single chest.
	ringMaxLoot = 10
	#The minimum number of rings that can be found inside a single chest. Values below 0 decrease the chance of the rings appearing.
	ringMinLoot = 1

["Rings Locations"]
	ringLocationPoisonResistance = "dungeons_plus:chests/warped_garden/common;minecraft:chests/simple_dungeon;minecraft:chests/jungle_temple;minecraft:chests/end_city_treasure;minecraft:chests/shipwreck_treasure;minecraft:chests/bastion_treasure;minecraft:chests/bastion_bridge"
	ringLocationKnockbackResistance = "dungeons_plus:chests/warped_garden/common;minecraft:chests/simple_dungeon;minecraft:chests/end_city_treasure;minecraft:chests/bastion_bridge;minecraft:chests/nether_bridge"
	ringLocationJumpBoost = "dungeons_plus:chests/warped_garden/common;minecraft:chests/simple_dungeon;minecraft:chests/end_city_treasure;minecraft:chests/igloo_chest;minecraft:chests/desert_pyramid"
	ringLocationDolphin = "dungeons_plus:chests/warped_garden/common;minecraft:chests/simple_dungeon;minecraft:chests/underwater_ruin_big;minecraft:chests/underwater_run_small;minecraft:chests/buried_treasure"
	ringLocationGrowth = "dungeons_plus:chests/warped_garden/common;minecraft:chests/simple_dungeon;minecraft:chests/jungle_temple"
	ringLocationFlight = "dungeons_plus:chests/warped_garden/common;minecraft:chests/simple_dungeon;minecraft:chests/end_city_treasure"
	ringLocationWaterWalking = "dungeons_plus:chests/warped_garden/common;minecraft:chests/simple_dungeon;minecraft:chests/underwater_ruin_big;minecraft:chests/underwater_run_small;minecraft:chests/buried_treasure"
	ringLocationLuck = "dungeons_plus:chests/warped_garden/common;minecraft:chests/simple_dungeon;minecraft:chests/jungle_temple"
	ringLocationUndying = "dungeons_plus:chests/warped_garden/common;minecraft:chests/simple_dungeon;minecraft:chests/woodland_mansion"
	ringLocationRegeneration = "dungeons_plus:chests/warped_garden/common;minecraft:chests/simple_dungeon;minecraft:chests/stronghold_corridor;minecraft:chests/stronghold_library"
	ringLocationMining = "dungeons_plus:chests/warped_garden/common;minecraft:chests/simple_dungeon;minecraft:chests/abandoned_mineshaft"
	ringLocationSpeed = "dungeons_plus:chests/warped_garden/common;minecraft:chests/spawn_bonus_chest;minecraft:chests/simple_dungeon;minecraft:chests/buried_treasure"
	ringLocationHealth = "dungeons_plus:chests/warped_garden/common;minecraft:chests/simple_dungeon;minecraft:chests/end_city_treasure;minecraft:chests/bastion_treasure;minecraft:chests/stronghold_library"
	ringLocationHungerless = "dungeons_plus:chests/warped_garden/common;minecraft:chests/simple_dungeon;minecraft:chests/village/village_butcher;minecraft:chests/end_city_treasure;minecraft:chests/woodland_mansion"
	ringLocationSlowResistance = "dungeons_plus:chests/warped_garden/common;minecraft:chests/simple_dungeon;minecraft:chests/end_city_treasure;minecraft:chests/shipwreck_treasure;minecraft:chests/bastion_treasure;minecraft:chests/bastion_bridge"
	ringLocationFireResistance = "dungeons_plus:chests/warped_garden/common;minecraft:chests/simple_dungeon;minecraft:chests/nether_bridge;minecraft:chests/ruined_portal;minecraft:chests/bastion_treasure"
	ringLocationStrength = "dungeons_plus:chests/warped_garden/common;minecraft:chests/simple_dungeon;minecraft:chests/stronghold_library;minecraft:chests/stronghold_corridor;minecraft:chests/stronghold_crossing;minecraft:chests/bastion_treasure;minecraft:chests/bastion_bridge;minecraft:chests/pillager_outpost"
	ringLocationNightVision = "dungeons_plus:chests/warped_garden/common;minecraft:chests/spawn_bonus_chest;minecraft:chests/simple_dungeon;minecraft:chests/abandoned_mineshaft"
	ringLocationWaterBreathing = "dungeons_plus:chests/warped_garden/common;minecraft:chests/simple_dungeon;minecraft:chests/spawn_bonus_chest;minecraft:chests/underwater_ruin_big;minecraft:chests/underwater_run_small;minecraft:chests/buried_treasure"
	ringLocationExperience = "dungeons_plus:chests/warped_garden/common;minecraft:chests/simple_dungeon;minecraft:chests/spawn_bonus_chest;minecraft:chests/simple_dungeon;minecraft:chests/buried_treasure;minecraft:chests/ruined_portal"
	ringLocationWither = "dungeons_plus:chests/warped_garden/common;minecraft:chests/simple_dungeon;minecraft:chests/bastion_treasure"
	ringLocationSlowFalling = "dungeons_plus:chests/warped_garden/common;minecraft:chests/simple_dungeon;minecraft:chests/buried_treasure;minecraft:chests/end_city_treasure"
	ringLocationInvisibility = "dungeons_plus:chests/warped_garden/common;minecraft:chests/simple_dungeon;minecraft:chests/abandoned_mineshaft;minecraft:chests/buried_treasure"
	ringLocationMagnetism = "dungeons_plus:chests/warped_garden/common;minecraft:chests/spawn_bonus_chest;minecraft:chests/simple_dungeon;minecraft:chests/buried_treasure;minecraft:chests/ruined_portal"
	ringLocationSponge = "dungeons_plus:chests/warped_garden/common;minecraft:chests/simple_dungeon;minecraft:chests/underwater_ruin_big;minecraft:chests/underwater_run_small"
```

</details>
